/*##############################################################################################
#                                                                                              #
#     #############       #############       #############       ####                ####     #
#    #             #     #             #     #             #     #    #              #    #    #
#    #    #####    #     #    #########      #    #####    #     #    #              #    #    #
#    #    #   #    #     #    #              #    #   #    #     #    #              #    #    #
#    #    #####    #     #    #              #    #####    #     #    #              #    #    #
#    #             #     #    #########      #             #     #    #              #    #    #
#    #             #     #             #     #             #     #    #              #    #    #
#    #    #####    #      #########    #     #    #####    #     #    #              #    #    #
#    #    #   #    #              #    #     #    #   #    #     #    #              #    #    #
#    #    #   #    #      #########    #     #    #   #    #     #    #########      #    #    #
#    #    #   #    #     #             #     #    #   #    #     #             #     #    #    #
#     ####     ####       #############       ####     ####       #############       ####     #
#                                                                                              #
#   Author: Stefano Rebughini <ste.rebu@outlook.it>                                            #
#                                                                                              #
################################################################################################
#                                                                                              #
#   License                                                                                    #
#                                                                                              #
#   This file is part of ASALI.                                                                #
#                                                                                              #
#   ASALI is free software you can redistribute it and/or modify                               #
#   it under the terms of the GNU General Public License as published by                       #
#   the Free Software Foundation, either version 3 of the License, or                          #
#   (at your option) any later version.                                                        #
#                                                                                              #
#   ASALI is distributed in the hope that it will be useful,                                   #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of                             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                              #
#   GNU General Public License for more details.                                               #
#                                                                                              #
#   You should have received a copy of the GNU General Public License                          #
#   along with ASALI. If not, see <http://www.gnu.org/licenses/>.                              #
#                                                                                              #
##############################################################################################*/


{
    beer_.push_back("<i>Now is the time to drink!</i>\n[Horace]");
    beer_.push_back("<i>Beer is the proof that god loves us and wants us to be happy.</i>\n[B. Franklin]");
    beer_.push_back("<i>Sobriety diminishes, discriminates and says no; drunkenness expands, unites and says yes.</i>\n[W. James]");
    beer_.push_back("<i>Give a man a beer, waste an hour, teach a man to brew, and waste a lifetime!</i>\n[B. Owen]");
    beer_.push_back("<i>A man's got to believe in something. I believe I'll have another drink.</i>\n[W. C. Fields]");
    beer_.push_back("<i>Beer seems like an even better idea after you've had some beer.</i>\n[S. Hall]");
    beer_.push_back("<i>Alcohol is not the answer to life's question...at least it helps you forget the question.</i>\n[V. Mallya]");
    beer_.push_back("<i>God has a brown voice, as soft and full as beer.</i>\n[A. Sexton]");
    beer_.push_back("<i>Come, landlord, fill a flowing bowl until it does run over;\ntonight we will all merry be - tomorrow we'll get sober.</i>\n[J. Fletcher]");
    beer_.push_back("<i>Good people drink good beer.</i>\n[H. S. Thompson]");
    beer_.push_back("<i>Fermentation equals civilisation.</i>\n[J. Ciardi]");
    beer_.push_back("<i>Stay with the beer. Beer is continuous blood. A continuous lover.</i>\n[C. Bukowski]");
    beer_.push_back("<i>The drink you like the best should be be the drink you drink the most.</i>\n[J. B. Burgess]");
    beer_.push_back("<i>All is fair in love and beer.</i>\n[Anonymous]");
    beer_.push_back("<i>Nothing ever tasted better than a cold beer on a beautifull afternoon\nwith nothing to look forward to than more of the same.</i>\n[H. Hood]");
    beer_.push_back("<i>When I drink, I think; and when I think, I drink.</i>\n[F. Rabelais]");
    beer_.push_back("<i>Quaintest thoughts - queerest fancies come to life and fade away;\nwhat care I how time advances?I am drinking today.</i>\n[E. A. Poe]");
    beer_.push_back("<i>No soldier can fight unless he is properly fed on beef and beer.</i>\n[J. Churchill]");
    beer_.push_back("<i>Keeping one's guest supplied with liquor is the first law of hospitality.</i>\n[M. Way]");
    beer_.push_back("<i>The church is near, but the road is icy. The bar is far, but I will walk carefully.</i>\n[Russian proverb]");
    beer_.push_back("<i>God made yeast, as well as dough, and loves fermantation just as dearly as he loves vegetation.</i>\n[R. W. Emerson]");
    beer_.push_back("<i>When I read about the evils of drinking, I gave up reading.</i>\n[H. Youngman]");
    beer_.push_back("<i>In wine there is wisdom, in beer there is freedom, in water there is bacteria.</i>\n[B. Franklin]");
    beer_.push_back("<i>If this dogs do you bite, soon as out of your bed, take a hair of the tail in the morning.</i>\n[Scottish proverb]");
    beer_.push_back("<i>Alcohol, taken in sufficient quantities, may produce all the effects of drunkenness.</i>\n[O. Wilde]");
    beer_.push_back("<i>Meet me down in the bar! We'll drink breakfast together.</i>\n[W. C. Fields]");
    beer_.push_back("<i>A drink a day keeps the shrink away.</i>\n[E. Abbey]");
    beer_.push_back("<i>Sometimes too much to drink is barely enough.</i>\n[M. Twain]");
    beer_.push_back("<i>I drink when I have occasion, and sometimes when I have no occasion.</i>\n[M. de Cervantes]");
    beer_.push_back("<i>Never trust a man who doesn't drink.</i>\n[J. Crumley]");
    beer_.push_back("<i>The mouth of a perfectly happy man is filled with beer.</i>\n[Ancient Egyptian proverb]");
    beer_.push_back("<i>The worse you are at thinking, the better you are at drinking.</i>\n[T. Goodkind]");
    beer_.push_back("<i>But I'm not so think as you drunk I am.</i>\n[J. C. Squire]");
}



