/*##############################################################################################
#                                                                                              #
#     #############       #############       #############       ####                ####     #
#    #             #     #             #     #             #     #    #              #    #    #
#    #    #####    #     #    #########      #    #####    #     #    #              #    #    #
#    #    #   #    #     #    #              #    #   #    #     #    #              #    #    #
#    #    #####    #     #    #              #    #####    #     #    #              #    #    #
#    #             #     #    #########      #             #     #    #              #    #    #
#    #             #     #             #     #             #     #    #              #    #    #
#    #    #####    #      #########    #     #    #####    #     #    #              #    #    #
#    #    #   #    #              #    #     #    #   #    #     #    #              #    #    #
#    #    #   #    #      #########    #     #    #   #    #     #    #########      #    #    #
#    #    #   #    #     #             #     #    #   #    #     #             #     #    #    #
#     ####     ####       #############       ####     ####       #############       ####     #
#                                                                                              #
#   Author: Stefano Rebughini <ste.rebu@outlook.it>                                            #
#                                                                                              #
################################################################################################
#                                                                                              #
#   License                                                                                    #
#                                                                                              #
#   This file is part of ASALI.                                                                #
#                                                                                              #
#   ASALI is free software you can redistribute it and/or modify                               #
#   it under the terms of the GNU General Public License as published by                       #
#   the Free Software Foundation, either version 3 of the License, or                          #
#   (at your option) any later version.                                                        #
#                                                                                              #
#   ASALI is distributed in the hope that it will be useful,                                   #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of                             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                              #
#   GNU General Public License for more details.                                               #
#                                                                                              #
#   You should have received a copy of the GNU General Public License                          #
#   along with ASALI. If not, see <http://www.gnu.org/licenses/>.                              #
#                                                                                              #
##############################################################################################*/


{
    beer_.push_back("<i>Now is the time to drink!</i>\n[Horace]");
    beer_.push_back("<i>Beer is the proof that god loves us and wants us to be happy.</i>\n[B. Franklin]");
    beer_.push_back("<i>Sobriety diminishes, discriminates and says no; drunkenness expands, unites and says yes.</i>\n[W. James]");
    beer_.push_back("<i>Give a man a beer, waste an hour, teach a man to brew, and waste a lifetime!</i>\n[B. Owen]");
    beer_.push_back("<i>A man's got to believe in something. I believe I'll have another drink.</i>\n[W. C. Fields]");
    beer_.push_back("<i>Beer seems like an even better idea after you've had some beer.</i>\n[S. Hall]");
    beer_.push_back("<i>Alcohol is not the answer to life's question...at least it helps you forget the question.</i>\n[V. Mallya]");
    beer_.push_back("<i>God has a brown voice, as soft and full as beer.</i>\n[A. Sexton]");
    beer_.push_back("<i>Come, landlord, fill a flowing bowl until it does run over;\ntonight we will all merry be - tomorrow we'll get sober.</i>\n[J. Fletcher]");
    beer_.push_back("<i>Good people drink good beer.</i>\n[H. S. Thompson]");
    beer_.push_back("<i>Fermentation equals civilisation.</i>\n[J. Ciardi]");
    beer_.push_back("<i>Stay with the beer. Beer is continuous blood. A continuous lover.</i>\n[C. Bukowski]");
    beer_.push_back("<i>The drink you like the best should be be the drink you drink the most.</i>\n[J. B. Burgess]");
    beer_.push_back("<i>All is fair in love and beer.</i>\n[Anonymous]");
    beer_.push_back("<i>Nothing ever tasted better than a cold beer on a beautifull afternoon\nwith nothing to look forward to than more of the same.</i>\n[H. Hood]");
    beer_.push_back("<i>When I drink, I think; and when I think, I drink.</i>\n[F. Rabelais]");
    beer_.push_back("<i>Quaintest thoughts - queerest fancies come to life and fade away;\nwhat care I how time advances?I am drinking today.</i>\n[E. A. Poe]");
    beer_.push_back("<i>No soldier can fight unless he is properly fed on beef and beer.</i>\n[J. Churchill]");
    beer_.push_back("<i>Keeping one's guest supplied with liquor is the first law of hospitality.</i>\n[M. Way]");
    beer_.push_back("<i>The church is near, but the road is icy. The bar is far, but I will walk carefully.</i>\n[Russian proverb]");
    beer_.push_back("<i>God made yeast, as well as dough, and loves fermantation just as dearly as he loves vegetation.</i>\n[R. W. Emerson]");
    beer_.push_back("<i>When I read about the evils of drinking, I gave up reading.</i>\n[H. Youngman]");
    beer_.push_back("<i>In wine there is wisdom, in beer there is freedom, in water there is bacteria.</i>\n[B. Franklin]");
    beer_.push_back("<i>If this dogs do you bite, soon as out of your bed, take a hair of the tail in the morning.</i>\n[Scottish proverb]");
    beer_.push_back("<i>Alcohol, taken in sufficient quantities, may produce all the effects of drunkenness.</i>\n[O. Wilde]");
    beer_.push_back("<i>Meet me down in the bar! We'll drink breakfast together.</i>\n[W. C. Fields]");
    beer_.push_back("<i>A drink a day keeps the shrink away.</i>\n[E. Abbey]");
    beer_.push_back("<i>Sometimes too much to drink is barely enough.</i>\n[M. Twain]");
    beer_.push_back("<i>I drink when I have occasion, and sometimes when I have no occasion.</i>\n[M. de Cervantes]");
    beer_.push_back("<i>Never trust a man who doesn't drink.</i>\n[J. Crumley]");
    beer_.push_back("<i>The mouth of a perfectly happy man is filled with beer.</i>\n[Ancient Egyptian proverb]");
    beer_.push_back("<i>The worse you are at thinking, the better you are at drinking.</i>\n[T. Goodkind]");
    beer_.push_back("<i>But I'm not so think as you drunk I am.</i>\n[J. C. Squire]");
    beer_.push_back("<i>There’s alcohol in plant and tree.\nIt must be nature’s plan that there should be in fair degree some alcohol in man.</i>\n[ A. P. Herbert]");
    beer_.push_back("<i>Ale, man, ale’s the stuff to drink for fellows whom it hurts to think.</i>\n[A. E. Housman]");
    beer_.push_back("<i>Sober or blotto, this is your motto: keep muddling through.</i>\n[P. G. Wodehouse]");
    beer_.push_back("<i>Drink is the feast of reason and the flow of soul.</i>\n[A. Pope]");
    beer_.push_back("<i>I have taken more out of alcohol than alcohol has taken out of me.</i>\n[W. Churchill]");
    beer_.push_back("<i>The problem with the world is that everyone is a few drinks behind</i>.\n[H. Bogart]");
    beer_.push_back("<i>When I’m drunk, I bite.</i>\n[B. Midler]");
    beer_.push_back("<i>It takes only one drink to get me drunk. The trouble is, I can’t remember if it’s the thirteenth or the fourteenth.</i>\n[G. Burns]");
    beer_.push_back("<i>Abstainer: a weak person who yields to the temptation of denying himself a pleasure.</i>\n[A. Bierce]");
    beer_.push_back("<i>Drink what you want; drink what you’re able. If you are drinking with me, you’ll be under the table.</i>\n[Anonymous]");
    beer_.push_back("<i>May your glass be ever full, may the roof over your head be always strong,\nand may you be in heaven half an hour before the devil knows you’re dead.</i>\n[Irish toast]");
    beer_.push_back("<i>What harm in drinking can there be, since punch and life so well agree?</i>\n[T. Blacklock]");
    beer_.push_back("<i>Drinking is a way of ending the day.</i>\n[E. Hemingway]");
    beer_.push_back("<i>Health – what my friends are always drinking to before they fall down.</i>\n[P. Diller]");
    beer_.push_back("<i>Man, being reasonable, must get drunk; the best of life is but intoxication.</i>\n[Lord Byron]");
    beer_.push_back("<i>You have to drink, otherwise you’d go stark staring sober.</i>\n[K. Waterhouse]");
    beer_.push_back("<i>Alcohol is a misunderstood vitamin.</i>\n[P. G. Wodehouse]");
    beer_.push_back("<i>Woman first tempted man to eat; he took to drinking of his own accord.</i>\n[J. R. Kemble]");
    beer_.push_back("<i>If I had to live my life over, I’d live over a saloon.</i>\n[W. C. Fields]");
    beer_.push_back("<i>Topping beer off with wine – that’s fine!</i>\n[German proverb]");
    beer_.push_back("<i>What’s drinking?A mere pause from thinking!</i>\n[Lord Byron]");
    beer_.push_back("<i>Here’s to alcohol,the rose-coloured glasses of life.</i>\n[F. S. Fitzgerald]");
    beer_.push_back("<i>Milk is for babies, when you grown up you have to drink beer.</i>\n[A. Schwarzenegger]");
    beer_.push_back("<i>He was a wise man who invented beer.</i>\n[Plato]");
    beer_.push_back("<i>What two ideas are more inseparable than beer and britannia?</i>\n[S. Smith]");
    beer_.push_back("<i>You can’t be a real country unless you have a beer and an airline.</i>\n[F. Zappa]");
    beer_.push_back("<i>Beauty is in the eye of the beer holder.</i>\n[K. Friedman]");
    beer_.push_back("<i>Beer, it’s the best damn drink in the world.</i>\n[J. Nicholson]");
    beer_.push_back("<i>There is no such thing as a bad beer. It’s that some taste better than others.</i>\n[B. Carter]");
    beer_.push_back("<i>I’m gaining weight the right way: I’m drinking beer.</i>\n[J. Damon]");
    beer_.push_back("<i>I have respect for beer.</i>\n[R. Crowe]");
    beer_.push_back("<i>Let a man walk ten miles steadily on a hot summer’s day along a dusty english road,\nand he will soon discover why beer was invented.</i>\n[G. K. Chesterton]");
    beer_.push_back("<i>Not all chemical are bad. Without chemicals such as hydrogen and oxygen for example,\n there would be no way to make water, a vital ingredient in beer.</i>\n[D. Barry]");
    beer_.push_back("<i>Ah, drink again this river that is the taker-away of pain, and the giver-back of beauty!</i>\n[E. St. V. Millay]");
    beer_.push_back("<i>Give me a woman who loves beer and I will conquer the world.</i>\n[Kaiser Wilhelm II]");
    beer_.push_back("<i>No animal ever invented anything so bad as drunkenness – or so good as drink.</i>\n[G . K. Chesterton]");
    beer_.push_back("<i>Beer is not a good cocktail-party drink, especially in a home where you don’t know where the bathroom is.</i>\n[B. Carter]");
    beer_.push_back("<i>Beer makes you feel the way you ought to feel without beer.</i>\n[H. Lawson]");
    beer_.push_back("<i>Alcohol may be man’s worst enemy, but the bible says love your enemy.</i>\n[F. Sinatra]");
    beer_.push_back("<i>The sacred pint alone can unbind the tongue.</i>\n[J. Joyce]");
    beer_.push_back("<i>I’ve never been thrown out of a pub, but I’ve fallen into quite a few.</i>\n[B. Bellamacina]");
    beer_.push_back("<i>Beer, if drunk in moderation, softens the temper, cheers the spirit and promotes health.</i>\n[T. Jefferson]");
    beer_.push_back("<i>I only take a drink on two occasions – when I’m thirsty and when I’m not.</i>\n[B. Behan]");
    beer_.push_back("<i>Teetotallers lack the sympathy and generosity of men that drink.</i>\n[W. H. Davies]");
    beer_.push_back("<i>A man who lies about beer makes enemies.</i>\n[S. King]");
    beer_.push_back("<i>For a quart of ale is a dish for a king.</i>\n[W. Shakespeare]");
    beer_.push_back("<i>Without question, the greatest invention in the history of mankind is beer.</i>\n[D. Barry]");
    beer_.push_back("<i>A man ought to get drunk at least twice a year...so he won’t let himself get snotty about it.</i>\n[R. Chandler]");
    beer_.push_back("<i>You’re not drunk if you can lie on the floor without holding on.</i>\n[D. Martin]");
    beer_.push_back("<i>A woman drove me to drink and I didn’t even have the decency to thank her.</i>\n[W. C. Fields]");
    beer_.push_back("<i>Always do sober what you said you’d do drunk. That will teach you to keep your mouth shut.</i>\n[E. Hemingway]");
    beer_.push_back("<i>Twenty-four hours in a day, 24 beers in a case. Coincidence?</i>\n[S. Wright]");
    beer_.push_back("<i>Time is never wasted when you’re wasted all the time.</i>\n[C. Zandonella]");
    beer_.push_back("<i>A fine beer may be judged with only one sip, but it’s better to be thoroughly sure.</i>\n[Czech proverb]");
    beer_.push_back("<i>A man can hide all things, excepting twain – that he is drunk, and that he is in love.</i>\n[Antiphanes]");
    beer_.push_back("<i>I fear the man who drinks water and so remembers this morning what the rest of us said last night.</i>\n[Greek proverb]");
    beer_.push_back("<i>Too much work and no vacation, deserves at least a small libation.</i>\n[O. Wilde]");
    beer_.push_back("<i>He that drinketh strong beer and goes to bed tight mellow, lives as he ought to live and dies a hearty fellow.</i>\n[Traditional toast]");
    beer_.push_back("<i>Give my people plenty of beer, good beer, and cheap beer, and you will have no  revolution among them.</i>\n[Queen Victoria]");
    beer_.push_back("<i>If you ever reach total enlightenment while drinking beer, I bet it makes beer shoot out your nose.</i>\n[J. Handey]");
    beer_.push_back("<i>It takes beer to make thirst worthwhile.</i>\n[German proverb]");
    beer_.push_back("<i>Beer...A high and mighty liquor.</i>\n[Julius Caesar]");
    beer_.push_back("<i>He is not deserving the name of englishman who speaketh against ale, that is, good ale.</i>\n[G. Borrow]");
    beer_.push_back("<i>’ere’s to english women an’ a quart of english beer.</i>\n[R. Kipling]");
    beer_.push_back("<i>No poems can live long or please that are written by water-drinkers.</i>\n[Horace]");
    beer_.push_back("<i>Alcohol may not solve your problems, but neither will water or milk.</i>\n[Anonymous]");
    beer_.push_back("<i>Beer needs baseball, and baseball needs beer – it has always been thus.</i>\n[P. Richmond]");
    beer_.push_back("<i>I never met a pub I didn’t like.</i>\n[P. Slosberg]");
    beer_.push_back("<i>Fermentation may have been a greater discovery than fire.</i>\n[D. R. Wallace]");
    beer_.push_back("<i>Who does not love beer, wine, women and song remains a fool his whole life long.</i>\n[C. Worner]");
    beer_.push_back("<i>I envy people who drink – at least they know what to blame everything on.</i>\n[O. Levant]");
    beer_.push_back("<i>Oh, you hate your job?...There’s a support group for that. It’s called everybody, and they meet at the bar.</i>\n[D. Carey]");
    beer_.push_back("<i>Drink because you are happy, but never because you are miserable.</i>\n[G. K. Chesterton]");
    beer_.push_back("<i>Of course, I just said I was a writer.</i>\n[S. King on being asked if he drank]");
    beer_.push_back("<i>I would give all my fame for a pot of ale, and safety.</i>\n[W. Shakespeare]");
    beer_.push_back("<i>Ninety-nine per cent of all problems can be solved by money – and for the other 1 per cent there’s alcohol.</i>\n[Q. R. Bufogle]");
    beer_.push_back("<i>Ignorance is a lot like alcohol: the more you have of it, the less you are able to see its effect on you.</i>\n[J. M. Bylsma]");
    beer_.push_back("<i>Those who drink beer will think beer.</i>\n[W. Irving]");
    beer_.push_back("<i>I’m a drinker with writing problems.</i>\n[B. Behan]");
    beer_.push_back("<i>When you stop drinking,\nyou have to deal with this marvellous personality that started you drinking in the first place.</i>\n[J. Breslin]");
    beer_.push_back("<i>I never drink while I’m working, but after a few glasses I get ideas that would never have occurred to me dead sober.</i>\n[I. Shaw]");
    beer_.push_back("<i>The only cure for a real hangover is death.</i>\n[R. Benchley]");
    beer_.push_back("<i>I have fed purely upon ale; I have eat my ale, drank my ale, and I always sleep upon ale.</i>\n[G. Farquhar]");
    beer_.push_back("<i>Nothing gives a sensation better than a beer!Nothing builds a relation better than a beer!</i>\n[A. Dubey]");
    beer_.push_back("<i>Alcohol is like love. The first kiss is magic, the second is intimate, the third is routine.</i>\n[R. Chandler]");
    beer_.push_back("<i>Alcohol is the anesthesia by which we endure the operation of life.</i>\n[G. B. Shaw]");
    beer_.push_back("<i>Alcohol is necessary for a man so that he can have a good opinion of himself, undisturbed by the facts.</i>\n[F. P. Dunne]");
    beer_.push_back("<i>I drink to make other people more interesting.</i>\n[E. Hemingway]");
    beer_.push_back("<i>Even though a number of people have tried, no one has yet found a way to drink for a living.</i>\n[J. Kerr]");
    beer_.push_back("<i>Bacchus, n. a. convenient deity invented by the ancients as an excuse for getting drunk.</i>\n[A. Bierce]");
    beer_.push_back("<i>The worst thing about some men is that when they are not drunk they are sober.</i>\n[W. B. Yeats]");
    beer_.push_back("<i>I drink exactly as much as I want, and one drink more.</i>\n[H. L. Mencken]");
    beer_.push_back("<i>The drunk mind speaks the sober heart.</i>\n[Anonymous]");
    beer_.push_back("<i>Know thyself, especially thyself after a couple of drinks.</i>\n[R. Brault]");
    beer_.push_back("<i>Drunkenness is nothing but voluntary madness.</i>\n[Seneca the Younger]");
    beer_.push_back("<i>One more drink and I’d have been under the host!</i>\n[D. Parker]");
    beer_.push_back("<i>My grandmother is over 80 and still doesn’t need glasses. Drinks right out the bottle.</i>\n[H. Youngman]");
    beer_.push_back("<i>Drink the first. Sip the second slowly. Skip the third.</i>\n[K. Rockne]");
    beer_.push_back("<i>A little bit of beer is divine medicine.</i>\n[Paracelsus]");
    beer_.push_back("<i>I distrust camels, and anyone else who can go a week without a drink.</i>\n[J. E. Lewis]");
    beer_.push_back("<i>Most people hate the taste of beer to begin with.\nIt is, however, a prejudice that many people have been able to overcome.</i>\n[W. Churchill]");
    beer_.push_back("<i>But if at church they would give us some ale...we’d sing and we’d pray all the live-long day.</i>\n[W. Blake]");
    beer_.push_back("<i>When you’re thirsty and it seems that you could drink the entire ocean, that’s faith;\nwhen you start to drink and finish only a glass or two, that’s science.</i>\n[A. Chekhov]");
    beer_.push_back("<i>By the time a bartender knows what drink a man will have before he orders,\nthere is little else about him worth knowing.</i>\n[Don Marquis]");
    beer_.push_back("<i>Fishing, with me, has always been an excuse to drink in the daytime.</i>\n[J. Cannon]");
    beer_.push_back("<i>I have two ambitions in life: one is to drink every pub dry, the other is to sleep with every woman on earth.</i>\n[O. Reed]");
    beer_.push_back("<i>Did your mother never tell you not to drink on an empty head?</i>\n[B. Connolly]");
    beer_.push_back("<i>The best way to judge a pub is by the albums on its jukebox.</i>\n[N. Beauman]");
    beer_.push_back("<i>Of course one should not drink much, but often.</i>\n[H. de Toulouse-Lautrec]");
    beer_.push_back("<i>Drink not the third glass, which thou canst not tame, when once it is within theen.</i>\n[G. Herbert]");
    beer_.push_back("<i>It is not how much we have,but how much we enjoy, that makes happiness.</i>\n[C. Spurgeon]");
    beer_.push_back("<i>Simply enjoy life and the great pleasures that come with it.</i>\n[K. Kurkova]");
    beer_.push_back("<i>I have a theory that the secret of martial happiness is simple: drink in different pubs to your other half.</i>\n[J. Cooper]");
    beer_.push_back("<i>Beer speaks. People mumble.</i>\n[T. Magee]");
    beer_.push_back("<i>Love makes the world go round?Not at all. Whisky makes it go round twice as fast.</i>\n[C. Mackenzie]");
    beer_.push_back("<i>There is nothing for a case of nerves like a case of beer.</i>\n[J. Goldstein]");
    beer_.push_back("<i>The difference between a drunk and an alcoholic is that a drunk doesn/t have to attend all those meetings.</i>\n[A. Lewis]");
    beer_.push_back("<i>I’m not a heavy drinker, I can sometimes go for hours without touching a drop.</i>\n[N. Coward]");
    beer_.push_back("<i>Beer...An intoxicating golder brew that re-emerges virtually unchanged an hour later.</i>\n[R. Bayan]");
    beer_.push_back("<i>There is nothing which has been yet contrived by man,\nby which so much happiness is produced as by a good tavern or inn.</i>\n[S. Johnson]");
    beer_.push_back("<i>How much of our literature, our political life,\nour friendships and love affairs, depend on being able to talk peacefully in a bar!</i>\n[J. Wain]");
    beer_.push_back("<i>The pub is the internet. It’s where information is gathered, collated and addressed.</i>\n[R. Ifans]");
    beer_.push_back("<i>Shoulder the sky, my lad, and drink you ale.</i>\n[A. E. Housman]"); 
}



