version: "3"

services:
    asali:
        container_name: asali
        image: "asali:2.5.0"
        build:
            context: "./"
            dockerfile: "./Dockerfile"
            args:
                ASALI_USER: asaliuser
        environment:
            DISPLAY: ${DISPLAY}
            NO_AT_BRIDGE: 1
            XDG_RUNTIME_DIR: /tmp/runtime-${USER}
        user: 1000:1000
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./sharedFolder:/home/asaliuser/sharedFolder/
