/*##############################################################################################
#                                                                                              #
#     #############       #############       #############       ####                ####     #
#    #             #     #             #     #             #     #    #              #    #    #
#    #    #####    #     #    #########      #    #####    #     #    #              #    #    #
#    #    #   #    #     #    #              #    #   #    #     #    #              #    #    #
#    #    #####    #     #    #              #    #####    #     #    #              #    #    #
#    #             #     #    #########      #             #     #    #              #    #    #
#    #             #     #             #     #             #     #    #              #    #    #
#    #    #####    #      #########    #     #    #####    #     #    #              #    #    #
#    #    #   #    #              #    #     #    #   #    #     #    #              #    #    #
#    #    #   #    #      #########    #     #    #   #    #     #    #########      #    #    #
#    #    #   #    #     #             #     #    #   #    #     #             #     #    #    #
#     ####     ####       #############       ####     ####       #############       ####     #
#                                                                                              #
#   Author: Stefano Rebughini <ste.rebu@outlook.it>                                            #
#                                                                                              #
################################################################################################
#                                                                                              #
#   License                                                                                    #
#                                                                                              #
#   This file is part of ASALI.                                                                #
#                                                                                              #
#   ASALI is free software: you can redistribute it and/or modify                              #
#   it under the terms of the GNU General Public License as published by                       #
#   the Free Software Foundation, either version 3 of the License, or                          #
#   (at your option) any later version.                                                        #
#                                                                                              #
#   ASALI is distributed in the hope that it will be useful,                                   #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of                             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                              #
#   GNU General Public License for more details.                                               #
#                                                                                              #
#   You should have received a copy of the GNU General Public License                          #
#   along with ASALI. If not, see <http://www.gnu.org/licenses/>.                              #
#                                                                                              #
##############################################################################################*/
 
{
	transport_.name.push_back("AC3H4");
	transport_.geometry.push_back(1);
	transport_.LJpotential.push_back(252.000);
	transport_.LJdiameter.push_back(4.760);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(0.000);
	transport_.MW.push_back(40.0648);
}
 
{
	transport_.name.push_back("CH3COOH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(436.000);
	transport_.LJdiameter.push_back(3.970);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(2.000);
	transport_.MW.push_back(60.0526);
}
 
{
	transport_.name.push_back("CH3COCH3");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(411.000);
	transport_.LJdiameter.push_back(4.820);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(58.08);
}
 
{
	transport_.name.push_back("C2H3CHO");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(443.200);
	transport_.LJdiameter.push_back(4.120);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(56.0642);
}
 
{
	transport_.name.push_back("C2H5CHO");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(411.000);
	transport_.LJdiameter.push_back(4.820);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(58.08);
}
 
{
	transport_.name.push_back("C4H9CHO");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(500.000);
	transport_.LJdiameter.push_back(5.640);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(86.1338);
}
 
{
	transport_.name.push_back("AR");
	transport_.geometry.push_back(0);
	transport_.LJpotential.push_back(136.500);
	transport_.LJdiameter.push_back(3.330);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(0.000);
	transport_.MW.push_back(39.948);
}
 
{
	transport_.name.push_back("C6H5CH2OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(622.400);
	transport_.LJdiameter.push_back(5.530);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(108.14);
}
 
{
	transport_.name.push_back("C6H4O2");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(450.000);
	transport_.LJdiameter.push_back(5.500);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(108.097);
}
 
{
	transport_.name.push_back("C6H6");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(468.500);
	transport_.LJdiameter.push_back(5.230);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(10.30);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(78.1136);
}
 
{
	transport_.name.push_back("C6H5CHO");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(622.400);
	transport_.LJdiameter.push_back(5.530);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(106.124);
}
 
{
	transport_.name.push_back("C6H5C2H4C6H5");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(783.800);
	transport_.LJdiameter.push_back(6.640);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(182.265);
}
 
{
	transport_.name.push_back("NC4H8");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(355.000);
	transport_.LJdiameter.push_back(4.650);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(56.1075);
}
 
{
	transport_.name.push_back("C4H6");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(357.000);
	transport_.LJdiameter.push_back(5.180);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(54.0916);
}
 
{
	transport_.name.push_back("C12H8");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(689.800);
	transport_.LJdiameter.push_back(6.500);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(152.196);
}
 
{
	transport_.name.push_back("C2H2");
	transport_.geometry.push_back(1);
	transport_.LJpotential.push_back(209.000);
	transport_.LJdiameter.push_back(4.100);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(2.500);
	transport_.MW.push_back(26.0379);
}
 
{
	transport_.name.push_back("C2H4");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(280.800);
	transport_.LJdiameter.push_back(3.971);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.500);
	transport_.MW.push_back(28.0538);
}
 
{
	transport_.name.push_back("C2H6");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(252.300);
	transport_.LJdiameter.push_back(4.302);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.500);
	transport_.MW.push_back(30.0696);
}
 
{
	transport_.name.push_back("C3H6");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(307.800);
	transport_.LJdiameter.push_back(4.140);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(42.0806);
}
 
{
	transport_.name.push_back("C3H8");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(303.400);
	transport_.LJdiameter.push_back(4.810);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(44.0965);
}
 
{
	transport_.name.push_back("C4H2");
	transport_.geometry.push_back(1);
	transport_.LJpotential.push_back(357.000);
	transport_.LJdiameter.push_back(5.180);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(50.0599);
}
 
{
	transport_.name.push_back("C4H4");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(357.000);
	transport_.LJdiameter.push_back(5.180);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(52.0758);
}
 
{
	transport_.name.push_back("CYC5H4O");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(450.000);
	transport_.LJdiameter.push_back(5.500);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(80.0862);
}
 
{
	transport_.name.push_back("C6H5O");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(450.000);
	transport_.LJdiameter.push_back(5.500);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(93.1051);
}
 
{
	transport_.name.push_back("CYC6H10ONE");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(568.500);
	transport_.LJdiameter.push_back(5.230);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(10.30);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(98.1448);
}
 
{
	transport_.name.push_back("CYC5H8");
	transport_.geometry.push_back(1);
	transport_.LJpotential.push_back(408.000);
	transport_.LJdiameter.push_back(5.200);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(68.1185);
}
 
{
	transport_.name.push_back("CYC6H8");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(468.500);
	transport_.LJdiameter.push_back(5.230);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(10.30);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(80.1295);
}
 
{
	transport_.name.push_back("CYC6H12");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(468.500);
	transport_.LJdiameter.push_back(5.230);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(10.30);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(84.1613);
}
 
{
	transport_.name.push_back("CYC6H10");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(468.500);
	transport_.LJdiameter.push_back(5.230);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(10.30);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(82.1454);
}
 
{
	transport_.name.push_back("CH2CO");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(436.000);
	transport_.LJdiameter.push_back(3.970);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(2.000);
	transport_.MW.push_back(42.0373);
}
 
{
	transport_.name.push_back("CH2O");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(498.000);
	transport_.LJdiameter.push_back(3.590);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(2.000);
	transport_.MW.push_back(30.0263);
}
 
{
	transport_.name.push_back("CH3OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(481.800);
	transport_.LJdiameter.push_back(3.626);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(32.0422);
}
 
{
	transport_.name.push_back("CH4");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(141.400);
	transport_.LJdiameter.push_back(3.746);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(2.600);
	transport_.collision.push_back(13.000);
	transport_.MW.push_back(16.0428);
}
 
{
	transport_.name.push_back("CO");
	transport_.geometry.push_back(1);
	transport_.LJpotential.push_back(98.100);
	transport_.LJdiameter.push_back(3.650);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(1.950);
	transport_.collision.push_back(1.800);
	transport_.MW.push_back(28.0104);
}
 
{
	transport_.name.push_back("CO2");
	transport_.geometry.push_back(1);
	transport_.LJpotential.push_back(244.000);
	transport_.LJdiameter.push_back(3.763);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(2.650);
	transport_.collision.push_back(2.100);
	transport_.MW.push_back(44.0098);
}
 
{
	transport_.name.push_back("CYC5H6");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(408.000);
	transport_.LJdiameter.push_back(5.200);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(66.1026);
}
 
{
	transport_.name.push_back("MCPTD");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(408.000);
	transport_.LJdiameter.push_back(5.200);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(80.1295);
}
 
{
	transport_.name.push_back("CRESOL");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(621.100);
	transport_.LJdiameter.push_back(5.640);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(108.14);
}
 
{
	transport_.name.push_back("NC10H20");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(540.980);
	transport_.LJdiameter.push_back(7.150);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(140.269);
}
 
{
	transport_.name.push_back("C6H5CH2C6H5");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(712.6);
	transport_.LJdiameter.push_back(6.890);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(168.238);
}
 
{
	transport_.name.push_back("DIPE");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(432.000);
	transport_.LJdiameter.push_back(6.000);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(102.177);
}
 
{
	transport_.name.push_back("CH3OCH3");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(303.400);
	transport_.LJdiameter.push_back(4.810);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(46.069);
}
 
{
	transport_.name.push_back("CH3CH3C5H6");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(450.000);
	transport_.LJdiameter.push_back(5.500);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(96.1723);
}
 
{
	transport_.name.push_back("C6H5C2H5");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(523.600);
	transport_.LJdiameter.push_back(5.960);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(106.167);
}
 
{
	transport_.name.push_back("NC7H14");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(459.980);
	transport_.LJdiameter.push_back(6.310);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(98.1882);
}
 
{
	transport_.name.push_back("NC6H12");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(412.300);
	transport_.LJdiameter.push_back(5.349);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(84.1613);
}
 
{
	transport_.name.push_back("C5H9CHO");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(568.500);
	transport_.LJdiameter.push_back(5.230);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(10.30);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(98.1448);
}
 
{
	transport_.name.push_back("ETBE");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(432.000);
	transport_.LJdiameter.push_back(6.000);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(102.177);
}
 
{
	transport_.name.push_back("C2H5OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(362.600);
	transport_.LJdiameter.push_back(4.530);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.500);
	transport_.MW.push_back(46.069);
}
 
{
	transport_.name.push_back("C2H5OOH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(362.600);
	transport_.LJdiameter.push_back(4.530);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.500);
	transport_.MW.push_back(62.0684);
}
 
{
	transport_.name.push_back("C2H4O");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(362.600);
	transport_.LJdiameter.push_back(4.530);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.500);
	transport_.MW.push_back(44.0532);
}
 
{
	transport_.name.push_back("C6H5C2H");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(534.300);
	transport_.LJdiameter.push_back(5.710);
	transport_.dipole.push_back(0.770);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(102.136);
}
 
{
	transport_.name.push_back("BIPHENYL");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(676.5);
	transport_.LJdiameter.push_back(6.310);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(154.211);
}
 
{
	transport_.name.push_back("C14H10");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(772.0);
	transport_.LJdiameter.push_back(6.960);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(38.80);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(178.233);
}
 
{
	transport_.name.push_back("C6H5OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(450.000);
	transport_.LJdiameter.push_back(5.500);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(94.113);
}
 
{
	transport_.name.push_back("FLUORENE");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(712.6);
	transport_.LJdiameter.push_back(6.890);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(166.222);
}
 
{
	transport_.name.push_back("C10H8");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(630.400);
	transport_.LJdiameter.push_back(6.180);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(16.50);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(128.174);
}
 
{
	transport_.name.push_back("H2");
	transport_.geometry.push_back(1);
	transport_.LJpotential.push_back(38.000);
	transport_.LJdiameter.push_back(2.920);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.790);
	transport_.collision.push_back(280.000);
	transport_.MW.push_back(2.01588);
}
 
{
	transport_.name.push_back("H2O");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(572.400);
	transport_.LJdiameter.push_back(2.605);
	transport_.dipole.push_back(1.844);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(4.000);
	transport_.MW.push_back(18.0153);
}
 
{
	transport_.name.push_back("H2O2");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(107.400);
	transport_.LJdiameter.push_back(3.458);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(3.800);
	transport_.MW.push_back(34.0147);
}
 
{
	transport_.name.push_back("HE");
	transport_.geometry.push_back(0);
	transport_.LJpotential.push_back(10.200);
	transport_.LJdiameter.push_back(2.576);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(0.000);
	transport_.MW.push_back(4.0026);
}
 
{
	transport_.name.push_back("IC4H8");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(355.000);
	transport_.LJdiameter.push_back(4.650);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(56.1075);
}
 
{
	transport_.name.push_back("IC3H7CHO");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(455.000);
	transport_.LJdiameter.push_back(4.650);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(72.1069);
}
 
{
	transport_.name.push_back("IC4H10");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(352.000);
	transport_.LJdiameter.push_back(5.240);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(58.1234);
}
 
{
	transport_.name.push_back("IC8H18");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(494.000);
	transport_.LJdiameter.push_back(6.170);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(114.231);
}
 
{
	transport_.name.push_back("INDENE");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(588.6);
	transport_.LJdiameter.push_back(5.960);
	transport_.dipole.push_back(0.650);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(116.163);
}
 
{
	transport_.name.push_back("IC3H7OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(482.146548);
	transport_.LJdiameter.push_back(5.008549665);
	transport_.dipole.push_back(1.66);
	transport_.polar.push_back(6.74);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(60.0959);
}
 
{
	transport_.name.push_back("IC5H10");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(408.000);
	transport_.LJdiameter.push_back(5.200);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(70.1344);
}
 
{
	transport_.name.push_back("IC3H5CHO");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(357.000);
	transport_.LJdiameter.push_back(5.180);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(70.091);
}
 
{
	transport_.name.push_back("MCYC6");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(495.300);
	transport_.LJdiameter.push_back(5.680);
	transport_.dipole.push_back(0.430);
	transport_.polar.push_back(12.30);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(98.1882);
}
 
{
	transport_.name.push_back("CH3CHO");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(436.000);
	transport_.LJdiameter.push_back(3.970);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(2.000);
	transport_.MW.push_back(44.0532);
}
 
{
	transport_.name.push_back("C10H7CH3");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(660.0);
	transport_.LJdiameter.push_back(6.350);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(142.2);
}
 
{
	transport_.name.push_back("CH3OOH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(481.800);
	transport_.LJdiameter.push_back(3.626);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(48.0416);
}
 
{
	transport_.name.push_back("MTBE");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(392.000);
	transport_.LJdiameter.push_back(5.640);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(88.1497);
}
 
{
	transport_.name.push_back("N2");
	transport_.geometry.push_back(1);
	transport_.LJpotential.push_back(97.530);
	transport_.LJdiameter.push_back(3.621);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(1.760);
	transport_.collision.push_back(4.000);
	transport_.MW.push_back(28.0135);
}
 
{
	transport_.name.push_back("C10H7OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(663.45);
	transport_.LJdiameter.push_back(6.362);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(144.173);
}
 
{
	transport_.name.push_back("C10H7CHO");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(663.45);
	transport_.LJdiameter.push_back(6.362);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(156.184);
}
 
{
	transport_.name.push_back("NC4H10");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(352.000);
	transport_.LJdiameter.push_back(5.240);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(58.1234);
}
 
{
	transport_.name.push_back("NC10H22");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(540.980);
	transport_.LJdiameter.push_back(7.150);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(142.285);
}
 
{
	transport_.name.push_back("NC12H26");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(580.000);
	transport_.LJdiameter.push_back(7.600);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(170.338);
}
 
{
	transport_.name.push_back("NC5H12");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(392.000);
	transport_.LJdiameter.push_back(5.640);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(72.1503);
}
 
{
	transport_.name.push_back("NC7H16");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(459.980);
	transport_.LJdiameter.push_back(6.310);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(100.204);
}
 
{
	transport_.name.push_back("NEOC5H12");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(392.000);
	transport_.LJdiameter.push_back(5.640);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(72.1503);
}
 
{
	transport_.name.push_back("O2");
	transport_.geometry.push_back(1);
	transport_.LJpotential.push_back(107.400);
	transport_.LJdiameter.push_back(3.458);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(1.600);
	transport_.collision.push_back(3.800);
	transport_.MW.push_back(31.9988);
}
 
{
	transport_.name.push_back("IC8H16");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(494.000);
	transport_.LJdiameter.push_back(6.170);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(112.215);
}
 
{
	transport_.name.push_back("NC5H10");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(408.000);
	transport_.LJdiameter.push_back(5.200);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(70.1344);
}
 
{
	transport_.name.push_back("PC3H4");
	transport_.geometry.push_back(1);
	transport_.LJpotential.push_back(252.000);
	transport_.LJdiameter.push_back(4.760);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(40.0648);
}
 
{
	transport_.name.push_back("CH3CO3H");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(443.200);
	transport_.LJdiameter.push_back(4.120);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(76.052);
}
 
{
	transport_.name.push_back("HCO3H");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(443.200);
	transport_.LJdiameter.push_back(4.120);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(62.0251);
}
 
{
	transport_.name.push_back("C3H6O");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(411.000);
	transport_.LJdiameter.push_back(4.820);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(58.08);
}
 
{
	transport_.name.push_back("C5H8");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(408.000);
	transport_.LJdiameter.push_back(5.200);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(68.1185);
}
 
{
	transport_.name.push_back("C16H10");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(834.9);
	transport_.LJdiameter.push_back(7.240);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(45.00);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(202.255);
}
 
{
	transport_.name.push_back("C6H5C2H3");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(546.200);
	transport_.LJdiameter.push_back(6.000);
	transport_.dipole.push_back(0.130);
	transport_.polar.push_back(15.00);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(104.152);
}
 
{
	transport_.name.push_back("TAME");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(432.000);
	transport_.LJdiameter.push_back(6.000);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(102.177);
}
 
{
	transport_.name.push_back("TETRALIN");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(630.400);
	transport_.LJdiameter.push_back(6.180);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(16.50);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(132.205);
}
 
{
	transport_.name.push_back("DECALIN");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(630.400);
	transport_.LJdiameter.push_back(6.180);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(16.50);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(138.253);
}
 
{
	transport_.name.push_back("C7H8");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(495.300);
	transport_.LJdiameter.push_back(5.680);
	transport_.dipole.push_back(0.430);
	transport_.polar.push_back(12.30);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(92.1405);
}
 
{
	transport_.name.push_back("XYLENE");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(523.600);
	transport_.LJdiameter.push_back(5.960);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(106.167);
}
 
{
	transport_.name.push_back("NC16H34");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(650.000);
	transport_.LJdiameter.push_back(8.350);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(226.446);
}
 
{
	transport_.name.push_back("N2H4");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(205.000);
	transport_.LJdiameter.push_back(4.230);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(4.260);
	transport_.collision.push_back(1.500);
	transport_.MW.push_back(32.0452);
}
 
{
	transport_.name.push_back("N2O");
	transport_.geometry.push_back(1);
	transport_.LJpotential.push_back(232.400);
	transport_.LJdiameter.push_back(3.828);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(44.0129);
}
 
{
	transport_.name.push_back("NH3");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(481.000);
	transport_.LJdiameter.push_back(2.920);
	transport_.dipole.push_back(1.470);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(10.000);
	transport_.MW.push_back(17.0306);
}
 
{
	transport_.name.push_back("NO");
	transport_.geometry.push_back(1);
	transport_.LJpotential.push_back(97.500);
	transport_.LJdiameter.push_back(3.621);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(1.760);
	transport_.collision.push_back(4.000);
	transport_.MW.push_back(30.0061);
}
 
{
	transport_.name.push_back("NO2");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(200.000);
	transport_.LJdiameter.push_back(3.500);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(46.0055);
}
 
{
	transport_.name.push_back("C3H5OOH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(407.800);
	transport_.LJdiameter.push_back(4.140);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(74.0794);
}
 
{
	transport_.name.push_back("NC3H7OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(482.146548);
	transport_.LJdiameter.push_back(5.008549665);
	transport_.dipole.push_back(1.66);
	transport_.polar.push_back(6.74);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(60.0959);
}
 
{
	transport_.name.push_back("N1C4H9OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(503.0722524);
	transport_.LJdiameter.push_back(5.339941638);
	transport_.dipole.push_back(1.67);
	transport_.polar.push_back(8.88);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(74.1228);
}
 
{
	transport_.name.push_back("N2C4H9OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(503.0722524);
	transport_.LJdiameter.push_back(5.339941638);
	transport_.dipole.push_back(1.67);
	transport_.polar.push_back(8.88);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(74.1228);
}
 
{
	transport_.name.push_back("MEK");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(454.0000000);
	transport_.LJdiameter.push_back(5.413000000);
	transport_.dipole.push_back(3.30);
	transport_.polar.push_back(0.00);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(72.1069);
}
 
{
	transport_.name.push_back("TC4H9OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(503.0722524);
	transport_.LJdiameter.push_back(5.339941638);
	transport_.dipole.push_back(1.67);
	transport_.polar.push_back(8.88);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(74.1228);
}
 
{
	transport_.name.push_back("IC4H9OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(503.0722524);
	transport_.LJdiameter.push_back(5.339941638);
	transport_.dipole.push_back(1.67);
	transport_.polar.push_back(8.88);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(74.1228);
}
 
{
	transport_.name.push_back("C4H7OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(503.0722524);
	transport_.LJdiameter.push_back(5.339941638);
	transport_.dipole.push_back(1.67);
	transport_.polar.push_back(8.88);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(72.1069);
}
 
{
	transport_.name.push_back("C3H5OH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(411.000);
	transport_.LJdiameter.push_back(4.820);
	transport_.dipole.push_back(0.00);
	transport_.polar.push_back(0.00);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(58.08);
}
 
{
	transport_.name.push_back("C10H10");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(630.400);
	transport_.LJdiameter.push_back(6.180);
	transport_.dipole.push_back(0.00);
	transport_.polar.push_back(16.50);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(130.189);
}
 
{
	transport_.name.push_back("BZFUR");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(630.400);
	transport_.LJdiameter.push_back(6.180);
	transport_.dipole.push_back(0.00);
	transport_.polar.push_back(16.50);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(118.135);
}
 
{
	transport_.name.push_back("TMBENZ");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(523.600);
	transport_.LJdiameter.push_back(5.960);
	transport_.dipole.push_back(0.00);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(120.194);
}
 
{
	transport_.name.push_back("NPBENZ");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(495.300);
	transport_.LJdiameter.push_back(5.680);
	transport_.dipole.push_back(0.430);
	transport_.polar.push_back(12.30);
	transport_.collision.push_back(1.0);
	transport_.MW.push_back(120.194);
}
 
{
	transport_.name.push_back("C6H5OCH3");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(450.000);
	transport_.LJdiameter.push_back(5.500);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(108.14);
}
 
{
	transport_.name.push_back("MB");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(468.000);
	transport_.LJdiameter.push_back(5.850);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(0.000);
	transport_.MW.push_back(102.133);
}
 
{
	transport_.name.push_back("MCROT");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(468.500);
	transport_.LJdiameter.push_back(5.230);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(100.117);
}
 
{
	transport_.name.push_back("MACRIL");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(430.100);
	transport_.LJdiameter.push_back(5.833);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(86.0904);
}
 
{
	transport_.name.push_back("DIBZFUR");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(676.5);
	transport_.LJdiameter.push_back(6.310);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(168.195);
}
 
{
	transport_.name.push_back("DIFENET");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(676.5);
	transport_.LJdiameter.push_back(6.310);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(170.211);
}
 
{
	transport_.name.push_back("C12H22");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(580.000);
	transport_.LJdiameter.push_back(7.600);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(166.307);
}
 
{
	transport_.name.push_back("BENZYNE");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(468.500);
	transport_.LJdiameter.push_back(5.230);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(10.30);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(76.0978);
}
 
{
	transport_.name.push_back("C2H2O2");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(470.600);
	transport_.LJdiameter.push_back(4.410);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.500);
	transport_.MW.push_back(58.0367);
}
 
{
	transport_.name.push_back("C4H6O2");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(496.000);
	transport_.LJdiameter.push_back(5.200);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(86.0904);
}
 
{
	transport_.name.push_back("C5H4O2");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(524.690);
	transport_.LJdiameter.push_back(5.653);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(96.0856);
}
 
{
	transport_.name.push_back("C5H8O4");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(568.500);
	transport_.LJdiameter.push_back(5.230);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(10.30);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(132.116);
}
 
{
	transport_.name.push_back("C6H10O5");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(568.500);
	transport_.LJdiameter.push_back(5.230);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(10.30);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(162.142);
}
 
{
	transport_.name.push_back("C8H10O3");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(621.100);
	transport_.LJdiameter.push_back(5.640);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(154.166);
}
 
{
	transport_.name.push_back("HCOOH");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(470.6);
	transport_.LJdiameter.push_back(3.855);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(46.0257);
}
 
{
	transport_.name.push_back("GLYCEROL");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(748.365);
	transport_.LJdiameter.push_back(5.200);
	transport_.dipole.push_back(1.93);
	transport_.polar.push_back(9.43);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(92.0947);
}
 
{
	transport_.name.push_back("C4H4O");
	transport_.geometry.push_back(2);
	transport_.LJpotential.push_back(429.630);
	transport_.LJdiameter.push_back(5.040);
	transport_.dipole.push_back(0.000);
	transport_.polar.push_back(0.000);
	transport_.collision.push_back(1.000);
	transport_.MW.push_back(68.0752);
}
 
