FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y
RUN apt-get install scons \
python3-ruamel.yaml \
python3-yaml \
build-essential \
libgtkmm-3.0-dev \
g++ \
gfortran \
git \
python \
libboost-dev \
cython \
python-dev \
python-numpy \
python-numpy-dev \
python-setuptools \
python3 \
python3-dev \
python3-setuptools \
python3-numpy \
cython3 \
python3-matplotlib -y

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

RUN mkdir /app
WORKDIR /app

RUN git clone https://github.com/Cantera/cantera.git

WORKDIR /app/cantera
RUN scons build system_sundials=n
RUN scons install


WORKDIR /app
RUN mkdir /app/asali
WORKDIR /app/asali
COPY src /app/asali/src
COPY include /app/asali/include
COPY chemkin /app/asali/chemkin
COPY images /app/asali/images
COPY database /app/asali/database
COPY Makefile /app/asali/.

RUN make all CANTERA_PREFIX=/usr/local/

# We need to define the command to launch when we are going to run the image.
# We use the keyword 'CMD' to do that.
# The following command will execute "python ./main.py".
CMD [ "./Asali" ]
