FROM ubuntu:20.04
MAINTAINER ASALIcode <ste.rebu@outlook.it>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y \
&& apt-get install --no-install-recommends scons \
ca-certificates \
build-essential \
g++ \
gfortran \
git \
libboost-dev \
libgtkmm-3.0-dev \
cython3 \
python3 \
python3-dev \
python3-setuptools \
python3-numpy \
python3-ruamel.yaml \
python3-yaml \
python3-matplotlib -y \
&& rm -rf /var/lib/apt/lists/* \
&& update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
&& mkdir /app \
&& mkdir /app/cantera \
&& mkdir /app/asali \
&& git clone https://github.com/Cantera/cantera.git /app/cantera/.

WORKDIR /app/cantera
RUN scons build system_sundials=n python_package=minimal cc_flags='-Os' matlab_toolbox=n doxygen_docs=n sphinx_docs=n debug=n && scons install

COPY . /app/asali/

WORKDIR /app/asali
RUN make all CANTERA_PREFIX=/usr/local/

ADD database /app/asali/database

CMD [ "./Asali" ]
