# A dockerfile must always start by importing the base image.
# We use the keyword 'FROM' to do that.
# In our example, we want import the python image.
# So we write 'python' for the image name and 'latest' for the version.
FROM python:3.8.7-buster

# In order to launch our python code, we must import it into our image.
# We use the keyword 'COPY' to do that.
# The first parameter 'main.py' is the name of the file on the host.
# The second parameter '/' is the path where to put the file on the image.
# Here we put the file at the image root folder.
RUN apt-get update -y
RUN apt-get install apt-utils g++  git scons build-essential gfortran libboost-dev python-setuptools -y

RUN apt-get install libgtkmm-3.0-dev -y

RUN mkdir /app
WORKDIR /app

RUN git clone https://github.com/Cantera/cantera.git

WORKDIR /app/cantera
RUN scons build system_sundials=n
RUN soncs install


WORKDIR /
RUN make all CANTERA_PREFIX=/usr/local/

# We need to define the command to launch when we are going to run the image.
# We use the keyword 'CMD' to do that.
# The following command will execute "python ./main.py".
CMD [ "./Asali.sh" ]
