EXE := ext/libasali.a

SRC_DIR := ext
OBJ_DIR := ext/obj

SRC := $(SRC_DIR)/Asali.cpp

OBJ := $(SRC:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)

CFLAGS := -fPIC -Os -s -std=c++11

.PHONY: clean
clean:
	$(RM) $(OBJ) $(EXE)

.PHONY: help
help:
	@echo available targets: clean all help

.PHONY: all
all: $(EXE)

$(OBJ_DIR):
	mkdir $@

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp | $(OBJ_DIR)
	$(CXX) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

$(EXE): $(OBJ)
	$(AR) r -o $@ $(LDFLAGS) $^ $(LDLIBS)


