from enum import Enum


class DataKeys(Enum):
    """
    Class to handle the keys of the data stored in DataStore
    """
    CHEMISTRY_FILE_PATH = "chemistry_file_path"
    UDK_FILE_PATH = "udk_file_path"
    GAS_PHASE_NAME = "gas_phase_name"
    SURFACE_PHASE_NAME = "surface_phase_name"
    OUTPUT_FILE_PATH = "output_file_path"
    INLET_NS = "inlet_number_of_species"
    INLET_SURF_NS = "inlet_numer_of_coverage_species"
    INLET_T = "inlet_temperature"
    INLET_P = "inlet_pressure"
    INLET_GAS_COMPOSITION = "inlet_gas_phase_composition"
    INITIAL_COVERAGE_COMPOSITION = "initial_coverage_composition"
    INITIAL_GAS_COMPOSITION = "initial_gas_composition"
    INITIAL_T = "initial_temperature"
    EQUILIBRIUM_T = "equilibrium_temperature"
    EQUILIBRIUM_P = "equilibrium_pressure"
    EQUILIBRIUM_X = "equilibrium_mole_fraction"
    EQUILIBRIUM_Y = "equilibrium_mass_fraction"
    EQUILIBRIUM_TYPE = "equilibrium_type"
    EQUILIBRIUM_N = "equilibrium_specie_names"
    GAS_SPECIES_NAMES = "gas_phase_specie_names"
    SURFACE_SPECIES_NAMES = "surface_phase_specie_names"
    RHO = "density"
    MU = "viscosity"
    MW = "molecular_weight"
    COND = "thermal_conductivity"
    DIFF_MIX = "mixture_diffusivity"
    CP = "specific_heat"
    H = "enthalpy"
    S = "entropy"
    GEOMETRY = "geometry"
    V = "velocity"
    L = "length"
    KN = "knudsen_number"
    VACUUM_SPECIE = "vacuum_specie"
    THERMO_FILE_PATH = "chemkin_thermo_file_path"
    TRANSPORT_FILE_PATH = "chemkin_transport_file_path"
    KINETIC_FILE_PATH = "chemkin_gas_kinetic_file_path"
    SURFACE_FILE_PATH = "chemkin_surface_file_path"
    USER_DEFINED_KINETIC_FILE_PATH = "asali_user_defined_kinetic_file_path"
    REACTOR_TYPE = "reactor_type"
    REACTOR_NAME = "reactor_name"
    REACTOR_PAGE_NAME = "reactor_page_name"
    VOLUME = "reactor_volume"
    ALFA = "reactor_catalytic_load"
    ENERGY_BALANCE = "energy_balance"
    TMAX = "integration_time"
    TSTEP = "integration_time_step"
    REACTOR_RESULTS = "reactor_results"
    TEMPERATURE_TYPES = "reactor_temperature_types"
    PLOT_AND_SAVE_COMPOSITION_TYPE = "plot_and_save_composition_type"
    COLORMAP = "plotting_color_map"
    GAS_SPECIES_NAMES_TO_BE_PLOTTED = "gas_species_names_to_be_plotted"
    SURFACE_SPECIES_NAMES_TO_BE_PLOTTED = "surface_species_names_to_be_plotted"
    TEMPERATURE_TO_BE_PLOTTED = "temperature_to_be_plotted"

