from enum import Enum


class DataKeys(Enum):
    """
    Class to handle the keys of the data stored in DataStore
    """
    CHEMISTRY_FILE_PATH = "chemistry_file_path"
    UDK_FILE_PATH = "udk_file_path"
    GAS_PHASE_NAME = "gas_phase_name"
    SURFACE_PHASE_NAME = "surface_phase_name"
    INLET_NS = "inlet_number_of_species"
    INLET_SURF_NS = "inlet_numer_of_coverage_species"
    INLET_T = "inlet_temperature"
    INLET_P = "inlet_pressure"
    INLET_GAS_COMPOSITION = "inlet_gas_phase_composition"
    INITIAL_COVERAGE_COMPOSITION = "initial_coverage_composition"
    INITIAL_GAS_COMPOSITION = "initial_gas_composition"
    INITIAL_T = "initial_temperature"
    EQUILIBRIUM_T = "equilibrium_temperature"
    EQUILIBRIUM_P = "equilibrium_pressure"
    EQUILIBRIUM_X = "equilibrium_mole_fraction"
    EQUILIBRIUM_Y = "equilibrium_mass_fraction"
    EQUILIBRIUM_TYPE = "equilibrium_type"
    EQUILIBRIUM_N = "equilibrium_specie_names"
    GAS_SPECIES_NAMES = "gas_phase_specie_names"
    SURFACE_SPECIES_NAMES = "surface_phase_specie_names"
    RHO = "density"
    MU = "viscosity"
    MW = "molecular_weight"
    COND = "thermal_conductivity"
    DIFF_MIX = "mixture_diffusivity"
    CP = "specific_heat"
    H = "enthalpy"
    S = "entropy"
    GEOMETRY = "geometry"
    V = "velocity"
    L = "length"
    KN = "knudsen_number"
    VACUUM_SPECIE = "vacuum_specie"
    THERMO_FILE_PATH = "chemkin_thermo_file_path"
    TRANSPORT_FILE_PATH = "chemkin_transport_file_path"
    KINETIC_FILE_PATH = "chemkin_gas_kinetic_file_path"
    SURFACE_FILE_PATH = "chemkin_surface_file_path"
    USER_DEFINED_KINETIC_FILE_PATH = "asali_user_defined_kinetic_file_path"
    REACTOR_TYPE = "reactor_type"
    VOLUME = "reactor_volume"
    ALFA = "reactor_catalytic_load"
    ENERGY_BALANCE = "energy_balance"
    TMAX = "integration_time"
    TSTEP = "integration_time_step"
    REACTOR_TIME = "reactor_time"
    REACTOR_RESULTS = "reactor_results"
    REACTOR_LENGTH = "reactor_length"

